---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'rhel8.hyperv.corvus.local/ansible-automation-platform-22/ee-supported-rhel8:latest'
  
ansible_config: '../ansible.cfg'

dependencies:
  galaxy: ansible-collections.yml
  python: python-packages.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    LABEL quay.expires-after="45d"
