---
collections:
  # ansible controller
  - name: ansible.controller
    version: 4.5.8
  - name: infra.controller_configuration
    version: 2.9.0
  # linux
  - name: ansible.posix
    version: 1.5.4
  - name: redhat.insights
    version: 1.3.0
  - name: redhat.rhel_system_roles
    version: 1.23.0
  - name: community.general
    version: 6.3.0
  - name: containers.podman
  # windows
  - name: chocolatey.chocolatey
  - name: community.windows
    version: 2.2.0
  - name: ansible.windows
    version: 2.4.0
  # cloud
  - name: azure.azcollection
    version: 2.6.0
  - name: amazon.aws
    version: 6.5.4
  # satellite
  - name: redhat.satellite
    version: 4.1.0
  - name: redhat.satellite_operations
    version: 3.0.0
  # idm
  - name: redhat.rhel_idm
    version: 1.13.2
  # network
  - name: ansible.netcommon
    version: 7.0.0
  # utils
  - name: ansible.utils
    version: 5.1.0
  # vmware
  - name: vmware.vmware
    version: 1.4.0
  # redhat_csp_download - deprecated
  - name: redhat.redhat_csp_download
    version: 1.2.2
  # middleware_automation
  # - name: middleware_automation.common
  - name: redhat.runtimes_common
    version: 1.2.1
...
