---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest'
  
ansible_config: '../ansible.cfg'

dependencies:
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    ADD playbooks /runner/project
    WORKDIR /runner/project
    ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    LABEL quay.expires-after="45d"
